name: r-base
channels:
  - conda-forge
  - nodefaults
  - r
dependencies:
  - r-asioheaders
  - r-base
  - r-devtools
  - r-essentials
  - r-fs
  - r-googledrive
  - r-googlesheets4
  - r-websocket
  - unzip
  # - rstudio>=1.1
