options(unzip = Sys.which("unzip"))
Sys.which("tar")
install.packages('remotes')
install.packages('devtools')
remotes::install_github('mitchelloharawild/icons@v0.1.0')
devtools::install_github("nstrayer/datadrivencv")
