name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch: # allows you to trigger the workflow run manually
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '3.4'
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install System wide dependencies
        run: |
          sudo apt install -y build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev r-cran-devtools
      - name: Install dependencies
        shell: Rscript {0}
        run: |
          # install.packages('remotes')
          # install.packages('devtools', dependencies=TRUE)
          devtools::install_github("nstrayer/datadrivencv")
      - name: Render Resume
        run: |
          cd src/
          Rscript render_cv.r

      - name: Commit up-to-date files
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add . && git commit -m "[skip ci] Add up-to-date files."

      - name: Push commit
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
