name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
        # with:
        #   r-version: '3.5.3'
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install System wide dependencies
        run: |
          sudo apt install -y build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
      - name: Install dependencies
        shell: Rscript {0}
        run: |
          install.packages('remotes')
          install.packages('devtools')
          devtools::install_github("nstrayer/datadrivencv")
