name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          channels: conda-forge,nodefaults
          mamba-version: '*'
          channel-priority: strict
          activate-environment: r-base
          auto-update-conda: false
          python-version: 3.9
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true

      - name: Set up conda environment
        run: |
          mamba env update -f environment.yaml

      - name: Install dependencies
        run: |
          Rscript install_dep.r

      - name: Render Resume
        run: |
          cd src/
          Rscript render_cv.r

      - uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: index.html
      - uses: actions/upload-artifact@v2
        with:
          name: banihirwe_cv.pdf
          path: banihirwe_cv.pdf

  update:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: index.html
          path: index.html
      - uses: actions/download-artifact@v2
        with:
          name: banihirwe_cv.pdf
          path: banihirwe_cv.pdf

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'build: update HTML and PDF files'
          title: Update HTML and PDF files
          body: |
            - Updates HTML and PDF files for changes on `main`
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-files
